version: '3.8'

services:
  sql-server-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1439:1433"

    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"

